@startuml Classes 

interface Usuario{
    + Nome{get;set;}
}
class Gerente{
    - Identificador: string
    - Senha : string
    + Identificador(){get;set}
    + Senha(){get;set}
}

Cliente -up-> Usuario
Gerente -up-> Usuario

class Produto{
    - Nome: string
    - Preco: decimal
    - Quantidade: int
    - Validade: DateTime

    + Nome(){get;set}
    + Preco(){get;set}
    + Quantidade(){get;set}
    + Validade(){get;set}
}
class Cadastrar{
    + Produto(){CriarJson()}
    + Cliente(){CriarJson()}

}

class GetPath{
    - basePath : string <<diretorio de execução /Debug/net9.0>>
    - raizProjeto : string <<"/">>
    + caminhoArquivo : string <<raizProjeto + nomeArquivo>>
   + CriarJson(nomeArquivo : string, conteudo List<string>)
}
@enduml