@startuml usecase
left to right direction
skinparam actorStyle awesome
usecase "se cadastrar" as cadastro

:Gerente: -right-> Cliente
:Cliente: -- cadastro

package TelaGerencia{
    usecase "cadastrar produto" as cadProd
    usecase "cadastrar cliente" as cadClient
}

package TelaCliente{
    usecase "comprar produto" as comprar
}

cadastro --> TelaGerencia
cadastro --> TelaCliente

@enduml